name: tv_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  json_serializable: ^4.1.3
  get: ^4.3.8
  equatable: ^2.0.0
  json_annotation: ^4.0.1
  retrofit: ^2.0.0
  logger: ^1.0.0
  shimmer: ^2.0.0
  flutter_card_swipper: ^0.4.0
  cached_network_image: ^3.0.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.0.0
  flutter_staggered_grid_view: ^0.4.0
  lottie: ^1.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  liquid_swipe: ^2.1.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  animated_text_kit: ^4.2.1
  dartz: ^0.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  retrofit_generator: ^2.0.0+1
  hive_generator: ^1.1.0



flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/

